spring:
  application:
    name: blog-master
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    # 数据库url地址
    url: jdbc:mysql://localhost:3306/blog
    # JDBC驱动
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #tomcat:
      #initial-size: 10
      #max-idle: 8
      #min-idle: 1
      #max-active: 20
      #max-wait: 60000

server:
  port: 56000

mybatis:
  type-aliases-package: com.jax.blog.model
  mapper-locations: classpath:mappers/*.xml